# Generated by Django 2.1.7 on 2019-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(help_text='Nombre del curso ', max_length=250)),
                ('codigoCurso', models.CharField(help_text='Codigo curso ', max_length=8)),
                ('numSeccionCurso', models.IntegerField(help_text='Numero seccion del curso')),
                ('anioCurso', models.IntegerField(help_text='Año del curso ')),
                ('semesterCurso', models.IntegerField(help_text='Semestre ')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='User',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
