# Generated by Django 2.1.3 on 2019-05-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlumno', models.CharField(max_length=200)),
                ('cursoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(max_length=200)),
                ('cursoGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Course')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.Grupo'),
        ),
    ]
