# Generated by Django 2.1.3 on 2019-05-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20190527_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_evaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('app_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('app_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('isAdmin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('myAdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuario_admin')),
            ],
        ),
    ]
