# Generated by Django 2.2 on 2019-05-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20190511_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_minima', models.TimeField(verbose_name='Duración Mínima')),
                ('duracion_maxima', models.TimeField(verbose_name='Duración Máxima')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('texto', models.CharField(max_length=200)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Criterio')),
            ],
        ),
        migrations.AddField(
            model_name='criterio',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Rubrica'),
        ),
    ]
