# Generated by Django 2.1.7 on 2019-05-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_evaluador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_evaluador',
            old_name='name',
            new_name='nombreEvaluador',
        ),
    ]
