# Generated by Django 2.1.3 on 2019-05-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAsignada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador', models.ManyToManyField(to='Usuarios.Usuario_evaluador')),
            ],
        ),
    ]
