# Generated by Django 2.1.7 on 2019-05-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20190511_2151'),
        ('Usuarios', '0004_auto_20190513_0435'),
    ]

    operations = [
    ]
